---
output:
  html_document:
    toc: yes
    theme: spacelab
    number_sections: no
    df_print: kable
    code_folding: show
---

```{r}

#| label = setup_config
#| echo = FALSE
#| message=FALSE
#| warning=FALSE
#| fig.width=8.66
#| fig.height=8.66
#| results="hide"

if (!require('devtools')) install.packages('devtools'); library('devtools')
if (!require('upstartr')) install.packages('upstartr'); library('upstartr')

run_config()

source(dir_src("functions.R"), local = knitr::knit_global())
# source(dir_src("finalize_plot.R"), local = knitr::knit_global())
# source(dir_src("theme.R"), local = knitr::knit_global())

# prevent Scientific Notation globally
options(scipen=999)
```

---
<!-- title: "`r getOption('startr.title')`" -->
<!-- author: '`r getOption('startr.author')`' -->
<!-- date: "`r format(Sys.Date(), '%B %d, %Y')`" -->
---


```{r}

#| label = run_base_code
#| echo = FALSE
#| message=FALSE
#| warning=FALSE
#| fig.width=8.66
#| fig.height=8.66
#| results="hide"
#| fig.show='hide'


run_process()
run_analyze()
source(dir_src("model.R"))
run_visualize()
```

------------------------------------------------------------------------

## Models 


### Linear models 

The results from this regression we see that when our regression is run with
 just the remoteness index, the R squared values are very low. This means that
 remoteness doesn't really explain this data very well on it's own.

After we add the under 19 population the model fits the data much better. It
 also changes the sign of the coefficient for the remoteness index. (need to
 come back and interpret what this means.)
 when the under 19 population is added, Lake St. Martin is dropped because we
 don't have the data for this.

Adding the staff ratio improves the R squared values but decreases the F stat.
 when adding the staff ratio Dakota Tipi is dropped (along with Lake St. Martin
 which was dropped because of the population data) because of missing data.
 (need to spend more time thinking about this)


```{r}

#| label = run_base_code
#| echo = FALSE
#| message=FALSE
#| warning=FALSE
#| fig.width=8.66
#| fig.height=8.66
#| results="as-is"

stargazer(list(lin_mod_1, lin_mod_2, lin_mod_3),
          type = 'text',
          title = "Comparison of Linear Cost Ratio models:",
          digits = 2)


```

### Log models

Pretty similar to linear model observations


```{r}

#| label = run_base_code
#| echo = FALSE
#| message=FALSE
#| warning=FALSE
#| fig.width=8.66
#| fig.height=8.66
#| results="as-is"



stargazer(list(log_mod_1, log_mod_2, log_mod_3),
          type = 'text',
          title = "Comparison of Logged Cost Ratio models:",
          digits = 2)
       

```

### Linear vs. Log models

When comparing the linear and logged models, the linear models fit better than the logged models.


```{r}

#| label = run_base_code
#| echo = FALSE
#| message=FALSE
#| warning=FALSE
#| fig.width=8.66
#| fig.height=8.66
#| results="as-is"

stargazer(list(lin_mod_2, log_mod_2, lin_mod_3, log_mod_3),
          type = 'text',
          title = "Comparison of Cost Ratio models:",
          digits = 2)


```

### Per capita spending removed   

The model with the remoteness index and the under 19 population has the best fit out of the three models.


```{r}

#| label = run_base_code
#| echo = FALSE
#| message=FALSE
#| warning=FALSE
#| fig.width=8.66
#| fig.height=8.66
#| results="as-is"

stargazer(list(lin_mod_npc_1, lin_mod_npc_2, lin_mod_npc_3),
          type = 'text',
          title = "Comparison of Linear Cost Ratio models (without per capita spending):",
          digits = 2)

```

### Linear with per capita spending removed


```{r}

#| label = run_base_code
#| echo = FALSE
#| message=FALSE
#| warning=FALSE
#| fig.width=8.66
#| fig.height=8.66
#| results="as-is"

stargazer(list(lin_mod_2, lin_mod_npc_2, lin_mod_3, lin_mod_npc_3),
          type = 'text',
          title = "Comparison of Linear Cost Ratio models (with and without per capita spending):",
          digits = 2)
          
```

### Logged models without per capita

Similar to the linear models, it looks like the model with the remoteness index and the under 19 population has the best fit out of the three models.


```{r}

#| label = run_base_code
#| echo = FALSE
#| message=FALSE
#| warning=FALSE
#| fig.width=8.66
#| fig.height=8.66
#| results="as-is"

stargazer(list(log_mod_npc_1, log_mod_npc_2, log_mod_npc_3),
          type = 'text',
          title = "Comparison of Logged Cost Ratio models (without per capita spending):",
          digits = 2)

```


### Logged models with per capita spending and without


```{r}

#| label = run_base_code
#| echo = FALSE
#| message=FALSE
#| warning=FALSE
#| fig.width=8.66
#| fig.height=8.66
#| results="as-is"

stargazer(list(log_mod_2, log_mod_npc_2, log_mod_3, log_mod_npc_3),
          type = 'text',
          title = "Comparison of Logged Cost Ratio models (with and without per capita spending):",
          digits = 2)

```

### Linear and logged models without per capita spending 

Seems like when looking at the cost ratio without per capita spending, the population ratio doesn't improve the model at all and that logging this data does seem to provide a better fit to the data



```{r}

#| label = run_base_code
#| echo = FALSE
#| message=FALSE
#| warning=FALSE
#| fig.width=8.66
#| fig.height=8.66
#| results="as-is"

stargazer(list(lin_mod_npc_2, log_mod_npc_2, lin_mod_npc_3, log_mod_npc_3),
          type = 'text',
          title = "Comparison of Cost Ratio models (without per capita spending):",
          digits = 2)


``` 


### Linear with per capita included and teacher ratio instead of staff ratio

When using teacher ratio, model 2 (without population ratio) has the best fit


```{r}

#| label = run_base_code
#| echo = FALSE
#| message=FALSE
#| warning=FALSE
#| fig.width=8.66
#| fig.height=8.66
#| results="as-is"

stargazer(list(lin_mod_1, lin_mod_2, lin_mod_tr_3),
          type = 'text',
          title = "Comparison of Linear Cost Ratio models (using teacher ratio):",
          digits = 2)


```


#### Linear model 3 (includes population ratio variable) using the staff ratio vs. using the teacher ratio

Using staff ratio rather than teacher ratio has a better fit, that being said adding staff ratio doesn't improve the fit either.



```{r}

#| label = run_base_code
#| echo = FALSE
#| message=FALSE
#| warning=FALSE
#| fig.width=8.66
#| fig.height=8.66
#| results="as-is"

stargazer(list(lin_mod_2, lin_mod_3, lin_mod_tr_3),
          type = 'text',
          title = "Comparison of Linear Cost Ratio models (staff ratio vs. teacher ratio):",
          digits = 2)


``` 


### Logged with teacher ratio not staff ratio

Has a better R squared value when population ratio is included but this also decreases the F statistic.


```{r}

#| label = run_base_code
#| echo = FALSE
#| message=FALSE
#| warning=FALSE
#| fig.width=8.66
#| fig.height=8.66
#| results="as-is"

stargazer(list(log_mod_1, log_mod_2, log_mod_tr_3),
          type = 'text',
          title = "Comparison of Logged Cost Ratio models (using teacher ratio):",
          digits = 2)

``` 

### Logged model 3 (population ratio) using  staff ratio vs. using the teacher ratio

Similar to the linear model comparing the population ratio additions, adding the population ratio reduced the f-stat in both cases. unlike the linear model the logged model has a better adjusted R squared value when the teacher population ratio is added. (need to think about this)




```{r}

#| label = run_base_code
#| echo = FALSE
#| message=FALSE
#| warning=FALSE
#| fig.width=8.66
#| fig.height=8.66
#| results="as-is"

stargazer(list(log_mod_2, log_mod_3, log_mod_tr_3),
          type = 'text',
          title = "Comparison of Logged Cost Ratio models (staff ratio vs. teacher ratio):",
          digits = 2)

```


### Linear and logged with staff vs. teacher ratios

When using the teacher ratio as the population ratio, adding that variable decreases the fit for both logged and linear versions.



```{r}

#| label = run_base_code
#| echo = FALSE
#| message=FALSE
#| warning=FALSE
#| fig.width=8.66
#| fig.height=8.66
#| results="as-is"

stargazer(list(lin_mod_2, log_mod_2, lin_mod_tr_3, log_mod_tr_3),
          type = 'text',
          title = "Comparison of Cost Ratio models (staff ratio vs. teacher ratio):",
          digits = 2)


```



------------------------------------------------------------------------

## Residual plots


```{r}

#| label = run_base_code
#| echo = FALSE
#| message=FALSE
#| warning=FALSE
#| fig.width=8.66
#| fig.height=8.66
#| results="as-is"

plot(lin_mod_1_plot)

cat("------------------------------------------------------------")

plot(lin_mod_2_plot)

cat("------------------------------------------------------------")

plot(lin_mod_3_plot)

cat("------------------------------------------------------------")

plot(lin_mod_tr_3_plot)

cat("------------------------------------------------------------")

plot(lin_mod_npc_1_plot)

cat("------------------------------------------------------------")

plot(lin_mod_npc_2_plot)

cat("------------------------------------------------------------")

plot(lin_mod_npc_3_plot)


```


------------------------------------------------------------------------

## Data

### band_populations

```{r}

#| label = run_base_code
#| echo = FALSE
#| message=FALSE
#| warning=FALSE
#| fig.width=8.66
#| fig.height=8.66
#| results="as-is"


cat(str(band_populations))
head(band_populations)

```

### indigenous_students_regular_school_programs

```{r}

#| label = run_base_code
#| echo = FALSE
#| message=FALSE
#| warning=FALSE
#| fig.width=8.66
#| fig.height=8.66
#| results="as-is"


cat(str(indigenous_students_regular_school_programs))
head(indigenous_students_regular_school_programs)

```

### remote_index

```{r}

#| label = run_base_code
#| echo = FALSE
#| message=FALSE
#| warning=FALSE
#| fig.width=8.66
#| fig.height=8.66
#| results="as-is"


cat(str(remote_index))
head(remote_index)

```

### amc_regional_funding_model

```{r}

#| label = run_base_code
#| echo = FALSE
#| message=FALSE
#| warning=FALSE
#| fig.width=8.66
#| fig.height=8.66
#| results="as-is"


cat(str(amc_regional_funding_model))
head(amc_regional_funding_model)

```

### amc_regional_funding_model_nopercap

```{r}

#| label = run_base_code
#| echo = FALSE
#| message=FALSE
#| warning=FALSE
#| fig.width=8.66
#| fig.height=8.66
#| results="as-is"


cat(str(amc_regional_funding_model_nopercap))
head(amc_regional_funding_model_nopercap)

```



### FNSS_regional_funding_model_summary

```{r}

#| label = run_base_code
#| echo = FALSE
#| message=FALSE
#| warning=FALSE
#| fig.width=8.66
#| fig.height=8.66
#| results="as-is"


cat(str(FNSS_regional_funding_model_summary))
head(FNSS_regional_funding_model_summary)

```



### FNSS_regional_funding_model_summary_per_capita

```{r}

#| label = run_base_code
#| echo = FALSE
#| message=FALSE
#| warning=FALSE
#| fig.width=8.66
#| fig.height=8.66
#| results="as-is"

cat(str(FNSS_regional_funding_model_summary_per_capita))
head(FNSS_regional_funding_model_summary_per_capita)

```

### mb_fn_schools

```{r}

#| label = run_base_code
#| echo = FALSE
#| message=FALSE
#| warning=FALSE
#| fig.width=8.66
#| fig.height=8.66
#| results="as-is"


cat(str(mb_fn_schools))
head(mb_fn_schools)

```




### cost_ratio

```{r}

#| label = run_base_code
#| echo = FALSE
#| message=FALSE
#| warning=FALSE
#| fig.width=8.66
#| fig.height=8.66
#| results="as-is"


cat(str(cost_ratio))
head(cost_ratio)

```


### df_for_cost_ratio_model

```{r}

#| label = run_base_code
#| echo = FALSE
#| message=FALSE
#| warning=FALSE
#| fig.width=8.66
#| fig.height=8.66
#| results="as-is"


cat(str(df_for_cost_ratio_model))
head(df_for_cost_ratio_model)

```

